# Gradle Properties
org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.71

# Mod Properties
mod_id=minethespire
mod_name=Mine the Spire
mod_license=GPL v3.0
mod_version=0.0.1
mod_group_id=forever.pajang.minethespire

# Dependency Properties
jade_version=26.0.10+neoforge
sodium_version=mc26.1.2-0.8.12-beta.2-neoforge
jei_version=29.6.2.31
curios_version=15.0.0-beta.2+26.1.2